In [17]:
from neuron import *
from encodingsource import *
from hsgs import *
from classical_neuron import *
from classical_pso import *
from sf import *
simulator = Aer.get_backend('qasm_simulator')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split


X = [[-1,-1,-1,-1], [1,-1,-1,-1],[1,1,1,-1], [1,1,-1,1]]
y = [0,0,1,1]

Xs_train, Xs_test, ys_train, ys_test = train_test_split(X, y, test_size=0.5, stratify=y,  random_state = 123)


print(Xs_train)
print(ys_train)

print(Xs_test)
print(ys_test)






[[1, 1, 1, -1], [1, -1, -1, -1]]
[1, 0]
[[1, 1, -1, 1], [-1, -1, -1, -1]]
[1, 0]


In [86]:

thresholdParameter = 0.5

def treinamentoNeuronio(operator,inputVector, weightVector, y_train):
    if (operator == "hsgs"):
        wBinaryBinary = deterministicBinarization(weightVector) # Binarization of Real weights
        neuron = createNeuron(inputVector, wBinaryBinary, operator)
        resultado = executeNeuron(neuron, simulator, threshold=None)
        deltaRule(inputVector, weightVector, threshold=thresholdParameter, lr=lrParameter, y_train=y_train, out=resultado)
        return resultado
    elif (operator == "encoding-weight"):
        #wBinaryBinary = deterministicBinarization(weightVector) # Binarization of Real weights
        neuron = createNeuron(inputVector, weightVector, operator)
        resultado = executeNeuron(neuron, simulator, threshold=None)
        deltaRule(inputVector, weightVector, threshold=thresholdParameter, lr=lrParameter, y_train=y_train, out=resultado)
        return resultado
    elif (operator == "classico"):
        inputVector = normalize(inputVector)
        weightVectorNormalized = normalize(weightVector)
        resultado = runClassicalNeuronReturnProbability(inputVector, weightVectorNormalized)
        print("saida do neuronio", resultado)
        #print(inputVector, weightVectorNormalized, weightVector, resultado)
        #print("valor esperado delta", y_train, "out", resultado)
        deltaRule(inputVector, weightVector, threshold=thresholdParameter, lr=lrParameter, y_train=y_train, out=resultado)
        return resultado
    else:
        print("tipo do NEURONIO INVALIDO")
        
        
nClasses = 2
weightVectorsClassico = [[-1, -1, -1, -1], [1, 1, 1, -1]]#[[1,1,1,1]]*nClasses#[[-1,-1,-1,-1]]*nClasses#[[-1,-1,1,-1]]*nClasses
nClasses = 2

n_epochs = 1000
for lrParameter in [0.1]:
    print("taxa de aprendizado",lrParameter )
    tamTreinamento = len(Xs_train)
    
    for iteration in range(n_epochs):
        erroClassico=0
        errosClassico = []

        for posicaoTreinamento in range(tamTreinamento):

            inputVector = Xs_train[posicaoTreinamento] # inputVectors[posicaoTreinamento]
            y_train = ys_train[posicaoTreinamento]
            
            print("input", inputVector,  "peso", weightVectorsClassico[y_train], y_train)

            operator = "classico"
            resultadoClassico = treinamentoNeuronio(operator,inputVector, weightVectorsClassico[y_train], y_train=1)
            
            #weightVectorsClassico[y_train] = normalize(weightVectorsClassico[y_train])


            #print(weightVectorsClassico[0], weightVectorsClassico[1])
            
            errosClassico.append(1-resultadoClassico)

            erroClassico += abs(1-resultadoClassico)####abs(resultadoHSGS_bin-y_train)
        #print("erro HSGS", erroHSGS, "erro encoding", erroEncoding)
        #print("erros", errosHSGS, errosEncoding)
    print("erros", erroClassico)



taxa de aprendizado 0.1
input [1, 1, 1, -1] peso [1, 1, 1, -1] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-1, -1, -1, -1] 0
saida do neuronio 0.25
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-1.0375, -0.9625, -0.9625, -0.9625] 0
saida do neuronio 0.22191603177176203
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-1.0764041984114119, -0.9235958015885881, -0.9235958015885881, -0.9235958015885881] 0
saida do neuronio 0.1930567618082908
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-1.1167513603209973, -0.8832486396790027, -0.8832486396790027, -0.8832486396790027] 0
saida do neuronio 0.16376728041016142
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-1.1585629963004893, -0.8414370036995108, -0.8414370036995108, -0.8414370036995108] 0
saida do neuronio 0.13452806598220937
i

input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.0054929981041028, 1.0054929981041025, 1.0054929981041025, 1.0054929981041025] 0
saida do neuronio 0.7513682344744069
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.0179245863803823, 1.017924586380382, 1.017924586380382, 1.017924586380382] 0
saida do neuronio 0.7544280751788613
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.030203182621439, 1.030203182621439, 1.030203182621439, 1.030203182621439] 0
saida do neuronio 0.757401029866081
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.042333131128135, 1.042333131128135, 1.042333131128135, 1.042333131128135] 0
saida do neuronio 0.7602908333693045
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.05431858945967, 1.0543185894596698

saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.687163523832944, 1.6871635238329463, 1.6871635238329463, 1.6871635238329463] 0
saida do neuronio 0.8644664274193135
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.6939402024619783, 1.6939402024619807, 1.6939402024619807, 1.6939402024619807] 0
saida do neuronio 0.8651897117991288
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.700680716872022, 1.7006807168720244, 1.7006807168720244, 1.7006807168720244] 0
saida do neuronio 0.8659037032608704
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.7073855317089786, 1.7073855317089808, 1.7073855317089808, 1.7073855317089808] 0
saida do neuronio 0.8666085882973364
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-3.714055102294112, 1.714055102294114, 1.714055102294114, 1.714055102294114]

saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.157213409321402, 2.1572134093214044, 2.1572134093214044, 2.1572134093214044] 0
saida do neuronio 0.9039788981282936
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.1620144644149875, 2.1620144644149897, 2.1620144644149897, 2.1620144644149897] 0
saida do neuronio 0.9042918227619686
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.166799873276889, 2.1667998732768914, 2.1667998732768914, 2.1667998732768914] 0
saida do neuronio 0.9046022612082856
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.1715697602164745, 2.171569760216477, 2.171569760216477, 2.171569760216477] 0
saida do neuronio 0.904910244583572
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.176324247987296, 2.1763242479872984, 2.1763242479872984, 2.1763242479872984] 

saida do neuronio 0.9290234185027972
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.636736604525267, 2.636736604525266, 2.636736604525266, 2.636736604525266] 0
saida do neuronio 0.9291725614552885
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.640277976452503, 2.6402779764525013, 2.6402779764525013, 2.6402779764525013] 0
saida do neuronio 0.9293209347523761
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.643811929714884, 2.6438119297148823, 2.6438119297148823, 2.6438119297148823] 0
saida do neuronio 0.9294685446809806
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.647338502480835, 2.6473385024808334, 2.6473385024808334, 2.6473385024808334] 0
saida do neuronio 0.929615397457986
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] pe

input [1, -1, -1, -1] peso [-4.84670630417339, 2.8467063041733875, 2.8467063041733875, 2.8467063041733875] 0
saida do neuronio 0.9372408207312488
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.849844263136827, 2.8498442631368253, 2.8498442631368253, 2.8498442631368253] 0
saida do neuronio 0.9373509819350236
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.852976714040076, 2.852976714040074, 2.852976714040074, 2.852976714040074] 0
saida do neuronio 0.9374606671629092
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.85610368068193, 2.8561036806819287, 2.8561036806819287, 2.8561036806819287] 0
saida do neuronio 0.9375698796750026
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-4.85922518669818, 2.8592251866981786, 2.8592251866981786, 2.8592251866981786] 0
saida do neuronio 0.9376

saida do neuronio 0.9446150507573471
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.079301791434819, 3.079301791434817, 3.079301791434817, 3.079301791434817] 0
saida do neuronio 0.944695980701019
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.082066992399768, 3.082066992399766, 3.082066992399766, 3.082066992399766] 0
saida do neuronio 0.9447766189638527
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.084828161451576, 3.0848281614515733, 3.0848281614515733, 3.0848281614515733] 0
saida do neuronio 0.9448569672144478
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.0875853130908535, 3.087585313090851, 3.087585313090851, 3.087585313090851] 0
saida do neuronio 0.9449370271083564
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-

input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.311083900439404, 3.3110839004394044, 3.3110839004394044, 3.3110839004394044] 0
saida do neuronio 0.9508981079641822
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.313538995041195, 3.313538995041195, 3.313538995041195, 3.313538995041195] 0
saida do neuronio 0.9509582100959626
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.315991084536397, 3.315991084536397, 3.315991084536397, 3.315991084536397] 0
saida do neuronio 0.9510181304695818
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.318440178012918, 3.318440178012918, 3.318440178012918, 3.318440178012918] 0
saida do neuronio 0.951077869958419
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.320886284514997, 3.320886284514997, 

saida do neuronio 0.9552913246093686
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.505392655323388, 3.5053926553233903, 3.5053926553233903, 3.5053926553233903] 0
saida do neuronio 0.955338986888106
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.507625705978983, 3.507625705978985, 3.507625705978985, 3.507625705978985] 0
saida do neuronio 0.9553865234849304
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.509856379804736, 3.5098563798047384, 3.5098563798047384, 3.5098563798047384] 0
saida do neuronio 0.9554339349268143
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.512084683058395, 3.5120846830583976, 3.5120846830583976, 3.5120846830583976] 0
saida do neuronio 0.9554812217377059
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] pe

saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.6954788451708875, 3.695478845170887, 3.695478845170887, 3.695478845170887] 0
saida do neuronio 0.9591326147931205
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.697522214431231, 3.697522214431231, 3.697522214431231, 3.697522214431231] 0
saida do neuronio 0.9591707697453381
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.699563675943964, 3.6995636759439643, 3.6995636759439643, 3.6995636759439643] 0
saida do neuronio 0.9592088364965812
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.701603234119135, 3.701603234119135, 3.701603234119135, 3.701603234119135] 0
saida do neuronio 0.959246815371248
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.703640893350573, 3.7036408933505727, 3.7036408933505727, 3.7036408933505727] 0
saida

input [1, -1, -1, -1] peso [-5.795393184027766, 3.795393184027761, 3.795393184027761, 3.795393184027761] 0
saida do neuronio 0.9609383190855918
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.797346268073486, 3.7973462680734813, 3.7973462680734813, 3.7973462680734813] 0
saida do neuronio 0.960972431600145
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.799297646493479, 3.799297646493474, 3.799297646493474, 3.799297646493474] 0
saida do neuronio 0.9610064703197361
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.801247322977493, 3.801247322977487, 3.801247322977487, 3.801247322977487] 0
saida do neuronio 0.9610404354984315
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.803195301202571, 3.8031953012025657, 3.8031953012025657, 3.8031953012025657] 0
saida do neuronio 0.96107432

saida do neuronio 0.9628324421530189
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.909679647978118, 3.909679647978114, 3.909679647978114, 3.909679647978114] 0
saida do neuronio 0.9628625995468271
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.911536518000776, 3.9115365180007724, 3.9115365180007724, 3.9115365180007724] 0
saida do neuronio 0.9628926962971689
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.913391883185918, 3.913391883185914, 3.913391883185914, 3.913391883185914] 0
saida do neuronio 0.962922732598182
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5.915245746556009, 3.915245746556005, 3.915245746556005, 3.915245746556005] 0
saida do neuronio 0.9629527086431536
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-5

saida do neuronio 0.9642969895650733
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-6.002521974423385, 4.002521974423382, 4.002521974423382, 4.002521974423382] 0
saida do neuronio 0.964324285051235
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-6.004305760170824, 4.00430576017082, 4.00430576017082, 4.00430576017082] 0
saida do neuronio 0.9643515288006816
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-6.00608818373079, 4.006088183730786, 4.006088183730786, 4.006088183730786] 0
saida do neuronio 0.9643787209695629
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-6.0078692476823115, 4.007869247682308, 4.007869247682308, 4.007869247682308] 0
saida do neuronio 0.9644058617133836
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-6.00964

input [1, -1, -1, -1] peso [-6.137752362567675, 4.137752362567672, 4.137752362567672, 4.137752362567672] 0
saida do neuronio 0.9663053809456679
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-6.139437093520392, 4.139437093520389, 4.139437093520389, 4.139437093520389] 0
saida do neuronio 0.9663290239125751
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-6.141120642324764, 4.14112064232476, 4.14112064232476, 4.14112064232476] 0
saida do neuronio 0.9663526257279894
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-6.142803011038365, 4.142803011038361, 4.142803011038361, 4.142803011038361] 0
saida do neuronio 0.9663761865059985
input [1, 1, 1, -1] peso [1.0, 1.0, 1.0, -1.0] 1
saida do neuronio 1.0
input [1, -1, -1, -1] peso [-6.144484201713064, 4.144484201713061, 4.144484201713061, 4.144484201713061] 0
saida do neuronio 0.9663997063602572

In [83]:
def deltaRule (inputVector, weightVector, threshold=0.09, lr=0.01, y_train=0, out=0):

    delta = y_train-out
    input_dim = len(weightVector)
    for j in range(input_dim):
        weightVector[j] =  weightVector[j] - (lr * delta * inputVector[j])     
        
inputVector = [ 0.5, -0.5, -0.5, -0.5]
weightVector = [ -0.5, -0.5, 0.5, 0.5]



for i in range(100):
    inputVector = normalize(inputVector)
    weightVector = normalize(weightVector)
    resultado = runClassicalNeuronReturnProbability(inputVector, weightVector)
    print(resultado)
    deltaRule(inputVector, weightVector, 0.1, 0.1, 1.0, resultado)
    print(weightVector)

0.25
[-0.5375 -0.4625  0.5375  0.5375]
0.30595720069404275
[-0.55176217 -0.41020998  0.55176217  0.55176217]
0.35831645131374473
[-0.56262553 -0.3623491   0.56262553  0.56262553]
0.40636488660010034
[-0.57083314 -0.31883729  0.57083314  0.57083314]
0.4499348087010363
[-0.57698906 -0.27941053  0.57698906  0.57698906]
0.4891759832169333
[-0.58156854 -0.24371849  0.58156854  0.58156854]
0.5244010378604128
[-0.58493865 -0.21138537  0.58493865  0.58493865]
0.5559894801650397
[-0.58738016 -0.18204432  0.58738016  0.58738016]
0.5843323903653992
[-0.58910703 -0.15535484  0.58910703  0.58910703]
0.6098030506537746
[-0.59028236 -0.13100995  0.59028236  0.59028236]
0.6327431643073856
[-0.59103071 -0.10873767  0.59103071  0.59103071]
0.6534579834697022
[-0.5914476  -0.08829943  0.5914476   0.5914476 ]
0.6722162518601972
[-0.59160661 -0.06948718  0.59160661  0.59160661]
0.6892525492117433
[-0.59156471 -0.05211994  0.59156471  0.59156471]
0.7047706634883212
[-0.59136623 -0.03604043  0.59136623  0.59

0.45902924965764025
[-0.55108111 -0.29820938  0.55108111  0.55108111]
[-0.57312965 -0.29820938  0.55108111  0.55108111]
[-0.57312965 -0.27616084  0.55108111  0.55108111]
[-0.57312965 -0.27616084  0.57312965  0.55108111]
[-0.57312965 -0.27616084  0.57312965  0.57312965]


0.4904662517470253
[-0.5562275  -0.26801659  0.5562275   0.5562275 ]
[-0.57670419 -0.26801659  0.5562275   0.5562275 ]
[-0.57670419 -0.24753991  0.5562275   0.5562275 ]
[-0.57670419 -0.24753991  0.57670419  0.5562275 ]
[-0.57670419 -0.24753991  0.57670419  0.57670419]


0.5188716714102747
[-0.56039867 -0.24054105  0.56039867  0.56039867]
[-0.57945508 -0.24054105  0.56039867  0.56039867]
[-0.57945508 -0.22148464  0.56039867  0.56039867]
[-0.57945508 -0.22148464  0.57945508  0.56039867]
[-0.57945508 -0.22148464  0.57945508  0.57945508]
